# Generated by Django 5.2.6 on 2025-09-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('bola', 'Bola'), ('sepatu', 'Sepatu'), ('jersey', 'Jersey'), ('kaos', 'Kaos'), ('celana', 'Celana')], default='bola', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
